#!/bin/bash

# Quick Test Commands for Bulk Recipe Update

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "BULK RECIPE UPDATE - QUICK TEST GUIDE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1. VERIFY PARSING FUNCTION WORKS"
echo "   Command: node test-parse-function.js"
echo "   Output: Should show 5/5 recipes parsed successfully"
echo ""

echo "2. START DEV SERVER (if not running)"
echo "   Command: npm run dev"
echo "   Port: 3000 (or 3001 if 3000 in use)"
echo ""

echo "3. TEST WITH cURL (POST CSV)"
echo "   Note: Requires authentication"
echo ""
echo "   Command:"
echo "   curl -X POST http://localhost:3000/api/admin/recipes/bulk-update \\"
echo "     -H 'Content-Type: text/csv' \\"
echo "     -H 'Cookie: <your-session-cookie>' \\"
echo "     --data-binary @'recipe-1042 updated (1).csv'"
echo ""
echo "   Or with Authorization header:"
echo "   curl -X POST http://localhost:3000/api/admin/recipes/bulk-update \\"
echo "     -H 'Content-Type: text/csv' \\"
echo "     -H 'Authorization: Bearer <token>' \\"
echo "     --data-binary @'recipe-1042 updated (1).csv'"
echo ""

echo "4. TEST WITH JavaScript/Node"
echo "   See test-bulk-update.js for example"
echo "   Command: node test-bulk-update.js"
echo ""

echo "5. CHECK API RESPONSE"
echo "   Expected successful response:"
echo "   {"
echo "     'success': true,"
echo "     'updated': 1041,"
echo "     'failed': 0,"
echo "     'noChanges': 0,"
echo "     'updateResults': ["
echo "       {"
echo "         '_id': '...',"
echo "         'status': 'success',"
echo "         'message': 'Recipe updated successfully',"
echo "         'changes': { ... }"
echo "       },"
echo "       ..."
echo "     ]"
echo "   }"
echo ""

echo "6. VERIFY DATABASE"
echo "   Command: mongosh"
echo "   Query:"
echo "   use dtps"
echo "   db.recipes.findOne({_id: ObjectId('6987274020c73b37ac76210f')})"
echo ""
echo "   Check: ingredients field should be Array, not String"
echo "   Should NOT see: ingredients: \"[{'name': ...}]\""
echo "   Should see: ingredients: [{\"name\": \"Basmati rice\", ...}]"
echo ""

echo "7. ERROR DEBUGGING"
echo "   If you see \"Cast to embedded failed\":"
echo "     • Parsing function not applied"
echo "     • Data format not recognized by parser"
echo "     • Check console logs for parsing errors"
echo ""
echo "   If you see \"RECIPE_NOT_FOUND\":"
echo "     • Check if _id format is correct"
echo "     • Verify ObjectId validity"
echo "     • May need uuid fallback"
echo ""
echo "   If you see \"Unauthorized\" (401):"
echo "     • Add authentication headers"
echo "     • Use valid session cookie"
echo "     • Or Bearer token if API key supported"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "KEY FILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test Data:"
echo "  recipe-1042 updated (1).csv"
echo ""
echo "API Routes:"
echo "  src/app/api/admin/recipes/bulk-update/route.ts"
echo "  src/app/api/admin/data/bulk-update/route.ts"
echo ""
echo "Test Scripts:"
echo "  test-parse-function.js (validates parsing function)"
echo "  test-bulk-update.js (API integration test)"
echo ""
echo "Documentation:"
echo "  IMPLEMENTATION_DETAILS.md (technical details)"
echo "  FINAL_BULK_UPDATE_STATUS.md (complete status)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
