export const COUNTRY_CODES = [
  { code: '+1', flag: '🇺🇸', country: 'United States' },
  { code: '+44', flag: '🇬🇧', country: 'United Kingdom' },
  { code: '+91', flag: '🇮🇳', country: 'India' },
  { code: '+86', flag: '🇨🇳', country: 'China' },
  { code: '+81', flag: '🇯🇵', country: 'Japan' },
  { code: '+82', flag: '🇰🇷', country: 'South Korea' },
  { code: '+33', flag: '🇫🇷', country: 'France' },
  { code: '+49', flag: '🇩🇪', country: 'Germany' },
  { code: '+39', flag: '🇮🇹', country: 'Italy' },
  { code: '+34', flag: '🇪🇸', country: 'Spain' },
  { code: '+61', flag: '🇦🇺', country: 'Australia' },
  { code: '+64', flag: '🇳🇿', country: 'New Zealand' },
  { code: '+55', flag: '🇧🇷', country: 'Brazil' },
  { code: '+56', flag: '🇨🇱', country: 'Chile' },
  { code: '+52', flag: '🇲🇽', country: 'Mexico' },
  { code: '+27', flag: '🇿🇦', country: 'South Africa' },
  { code: '+971', flag: '🇦🇪', country: 'United Arab Emirates' },
  { code: '+966', flag: '🇸🇦', country: 'Saudi Arabia' },
  { code: '+60', flag: '🇲🇾', country: 'Malaysia' },
  { code: '+65', flag: '🇸🇬', country: 'Singapore' },
  { code: '+66', flag: '🇹🇭', country: 'Thailand' },
  { code: '+62', flag: '🇮🇩', country: 'Indonesia' },
  { code: '+63', flag: '🇵🇭', country: 'Philippines' },
  { code: '+84', flag: '🇻🇳', country: 'Vietnam' },
  { code: '+880', flag: '🇧🇩', country: 'Bangladesh' },
  { code: '+92', flag: '🇵🇰', country: 'Pakistan' },
  { code: '+90', flag: '🇹🇷', country: 'Turkey' },
  { code: '+353', flag: '🇮🇪', country: 'Ireland' },
  { code: '+47', flag: '🇳🇴', country: 'Norway' },
  { code: '+46', flag: '🇸🇪', country: 'Sweden' },
  { code: '+45', flag: '🇩🇰', country: 'Denmark' },
  { code: '+358', flag: '🇫🇮', country: 'Finland' },
  { code: '+31', flag: '🇳🇱', country: 'Netherlands' },
  { code: '+41', flag: '🇨🇭', country: 'Switzerland' },
  { code: '+43', flag: '🇦🇹', country: 'Austria' },
  { code: '+32', flag: '🇧🇪', country: 'Belgium' },
  { code: '+36', flag: '🇭🇺', country: 'Hungary' },
  { code: '+48', flag: '🇵🇱', country: 'Poland' },
  { code: '+420', flag: '🇨🇿', country: 'Czech Republic' },
  { code: '+30', flag: '🇬🇷', country: 'Greece' },
  { code: '+7', flag: '🇷🇺', country: 'Russia' },
];
